language: python
python:
  - 3.6
cache: pip
install:
  - pip install -r requirements_travis.txt
script:
  - python3 ./tests/test_addComponent.py
  - python3 ./tests/test_addingInteractions.py
  - python3 ./tests/test_componentBuckets.py